displayName=Infoboxes Extended
author=kevetone
description=Extended customizability for Infoboxes.
tags=infobox,infoboxes,extended,customization,inverted,flipped
version=
plugins=com.infoboxes_extended.InfoboxesExtendedPlugin
build=standard